//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudsdale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloudsdale.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d71ed537.
        /// </summary>
        internal static string BugsenseApiKey {
            get {
                return ResourceManager.GetString("BugsenseApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/users.
        /// </summary>
        internal static string CloudJoin {
            get {
                return ResourceManager.GetString("CloudJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/users/{userid}.
        /// </summary>
        internal static string CloudLeave {
            get {
                return ResourceManager.GetString("CloudLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        internal static string CurrentApiVersion {
            get {
                return ResourceManager.GetString("CurrentApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/drops/search.json?q={query}.
        /// </summary>
        internal static string DropsSearchEndpoint {
            get {
                return ResourceManager.GetString("DropsSearchEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2a$10$7Pfcv89Q9c/9WMAk6ySfhu.
        /// </summary>
        internal static string EncryptionComplexifier {
            get {
                return ResourceManager.GetString("EncryptionComplexifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255258867845902.
        /// </summary>
        internal static string facebookAppId {
            get {
                return ResourceManager.GetString("facebookAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://assets.cloudsdale.org/assets/fallback/.
        /// </summary>
        internal static string fallbackBaseUrl {
            get {
                return ResourceManager.GetString("fallbackBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /clouds/{cloudid}/drops.
        /// </summary>
        internal static string FayeDropsChannel {
            get {
                return ResourceManager.GetString("FayeDropsChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /clouds/{cloudid}/chat/messages.
        /// </summary>
        internal static string FayeMessageChannel {
            get {
                return ResourceManager.GetString("FayeMessageChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;channel&quot;:&quot;/clouds/{cloudid}/presence&quot;,&quot;clientId&quot;:&quot;{clientid}&quot;,data:{user}}].
        /// </summary>
        internal static string FayePresence {
            get {
                return ResourceManager.GetString("FayePresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /clouds/{cloudid}/users.
        /// </summary>
        internal static string FayeUsersChannel {
            get {
                return ResourceManager.GetString("FayeUsersChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/users/{0}.json.
        /// </summary>
        internal static string getUserEndpoint {
            get {
                return ResourceManager.GetString("getUserEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ecc40133fddbd4eb0000001.
        /// </summary>
        internal static string HammockID {
            get {
                return ResourceManager.GetString("HammockID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $2a$10$7Pfcv89Q9c/9WMAk6ySfhu.
        /// </summary>
        internal static string InternalToken {
            get {
                return ResourceManager.GetString("InternalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/users/{userid}.json.
        /// </summary>
        internal static string JoinCloudEndpoint {
            get {
                return ResourceManager.GetString("JoinCloudEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/users/{userid}.json.
        /// </summary>
        internal static string LeaveCloudEndpoint {
            get {
                return ResourceManager.GetString("LeaveCloudEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/sessions.
        /// </summary>
        internal static string loginUrl {
            get {
                return ResourceManager.GetString("loginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://push.cloudsdale.org/push.
        /// </summary>
        internal static string longPollingUrl {
            get {
                return ResourceManager.GetString("longPollingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{&quot;oauth&quot;:{{&quot;client_type&quot;:&quot;wp7&quot;,&quot;provider&quot;:&quot;{0}&quot;,&quot;token&quot;:&quot;{1}&quot;,&quot;uid&quot;:&quot;{2}&quot;}}}}.
        /// </summary>
        internal static string OAuthFormat {
            get {
                return ResourceManager.GetString("OAuthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/popular.json.
        /// </summary>
        internal static string PopularCloudsEndpoint {
            get {
                return ResourceManager.GetString("PopularCloudsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/drops.json.
        /// </summary>
        internal static string PreviousDropsEndpoint {
            get {
                return ResourceManager.GetString("PreviousDropsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/chat/messages.json.
        /// </summary>
        internal static string PreviousMessagesEndpoint {
            get {
                return ResourceManager.GetString("PreviousMessagesEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ws://push.cloudsdale.org/push.
        /// </summary>
        internal static string pushUrl {
            get {
                return ResourceManager.GetString("pushUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/recent.json.
        /// </summary>
        internal static string RecentCloudsEndpoint {
            get {
                return ResourceManager.GetString("RecentCloudsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/search.json?q={query}.
        /// </summary>
        internal static string SearchCloudsEndpoint {
            get {
                return ResourceManager.GetString("SearchCloudsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/clouds/{cloudid}/chat/messages.
        /// </summary>
        internal static string SendEndpoint {
            get {
                return ResourceManager.GetString("SendEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.cloudsdale.org/v1/users/{userid}/clouds.json.
        /// </summary>
        internal static string UserCloudsEndpoint {
            get {
                return ResourceManager.GetString("UserCloudsEndpoint", resourceCulture);
            }
        }
    }
}
